#Server configuration
server:
  port: 8082
  
  #Application info
info: 
  application:
    name: API Gateway
    description: API Gateway
    
#Eureka service discovery configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#actuator configuration      
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      

#Spring boot configuration      
spring:
  application:
    name: api-gateway

#jwt keys   
jwt:
  public:
    key: classpath:/certs/public.pem       
          